curl https://projects.thecity.nyc/covid-19-deaths-img/Shaimeek_Frazier.jpg -o Shaimeek_Frazier.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/David_Rivera.jpeg -o David_Rivera.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Michelle_Alexander.jpg -o Michelle_Alexander.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Avinaash_Takdari.jpg -o Avinaash_Takdari.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Miguel_Almarante.jpg -o Miguel_Almarante.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Terrence_Darkim_Riley.jpg -o Terrence_Darkim_Riley.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Frantz_Vital.jpg -o Frantz_Vital.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Lynette_Bermudez.jpg -o Lynette_Bermudez.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Travis_Williams.jpg -o Travis_Williams.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Luke_Workoff.png -o Luke_Workoff.png
curl https://projects.thecity.nyc/covid-19-deaths-img/Ryan_Shea.jpeg -o Ryan_Shea.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Juan_Rodriguez.jpg -o Juan_Rodriguez.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Jonathon_Davis.png -o Jonathon_Davis.png
curl https://projects.thecity.nyc/covid-19-deaths-img/Joel_Gomez.jpg -o Joel_Gomez.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Lenin_Portillo.jpg -o Lenin_Portillo.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Dustin_Petrie.jpg -o Dustin_Petrie.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Robert_Simon.jpg -o Robert_Simon.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Rovin_Smith.jpeg -o Rovin_Smith.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Ajana_Wilkinson_Iwayemi.jpeg -o Ajana_Wilkinson_Iwayemi.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Clinton_Washington.jpg -o Clinton_Washington.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Robert_Cardona.PNG -o Robert_Cardona.PNG
curl https://projects.thecity.nyc/covid-19-deaths-img/Gianmarco_Bertolotti.png -o Gianmarco_Bertolotti.png
curl https://projects.thecity.nyc/covid-19-deaths-img/Danny_Camacho.jpg -o Danny_Camacho.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Oscar_Tapia_Sanchez.jpg -o Oscar_Tapia_Sanchez.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Pablo_Garcia.JPG -o Pablo_Garcia.JPG
curl https://projects.thecity.nyc/covid-19-deaths-img/Levester_Thompson.jpg -o Levester_Thompson.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Luis_Liz.jpeg -o Luis_Liz.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Evelyn_Rivera.jpg -o Evelyn_Rivera.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Warren_Bates.jpg -o Warren_Bates.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Cedric_Dixon.jpeg -o Cedric_Dixon.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Marcus_Overton.jpg -o Marcus_Overton.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Marisa_Williams.png -o Marisa_Williams.png
curl https://projects.thecity.nyc/covid-19-deaths-img/Randip_Minhas.JPG -o Randip_Minhas.JPG
curl https://projects.thecity.nyc/covid-19-deaths-img/Kelly_Wong.jpg -o Kelly_Wong.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Ruel_Forbes.PNG -o Ruel_Forbes.PNG
curl https://projects.thecity.nyc/covid-19-deaths-img/Eddy_Marquez.jpeg -o Eddy_Marquez.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Luis_Rivera.jpeg -o Luis_Rivera.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Kimberly_Wetzel.jpg -o Kimberly_Wetzel.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Robert_Nathan.jpg -o Robert_Nathan.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Jack_Polimeni.jpg -o Jack_Polimeni.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Robert_Papik.png -o Robert_Papik.png
curl https://projects.thecity.nyc/covid-19-deaths-img/Martin_Vidal_Rosete.jpg -o Martin_Vidal_Rosete.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Juan_Sanabria.jpg -o Juan_Sanabria.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Edward_Daniels.jpg -o Edward_Daniels.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Ramon_Furcal.jpg -o Ramon_Furcal.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Kenneth_Earl_Green_Jr.png -o Kenneth_Earl_Green_Jr.png
curl https://projects.thecity.nyc/covid-19-deaths-img/Adalberto_Lebron.jpeg -o Adalberto_Lebron.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Mark_Pompa.jpeg -o Mark_Pompa.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Juan_Vazquez.jpg -o Juan_Vazquez.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Charles_Burrows.jpg -o Charles_Burrows.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Kenneth_Green.jpg -o Kenneth_Green.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Victor_Heras.jpg -o Victor_Heras.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Arthur_Hurwitz.jpg -o Arthur_Hurwitz.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Maria_Mercader.jpg -o Maria_Mercader.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Bashir_Ajaz_Mohammed.jpeg -o Bashir_Ajaz_Mohammed.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Leonel_Tusa_Masaquiza.jpeg -o Leonel_Tusa_Masaquiza.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Gumercindo_Alicea.jpeg -o Gumercindo_Alicea.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Richard_Lenihan.jpg -o Richard_Lenihan.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Tracey_Murchison.jpg -o Tracey_Murchison.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Jose_Miguel_Cabrera_Garcia.jpg -o Jose_Miguel_Cabrera_Garcia.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Antonietta_Florio.png -o Antonietta_Florio.png
curl https://projects.thecity.nyc/covid-19-deaths-img/Jose_Hernandez.jpg -o Jose_Hernandez.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Thankachan_Mathai.jpg -o Thankachan_Mathai.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Tim_Montgomery.jpg -o Tim_Montgomery.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Michael_O'Connor.jpeg -o Michael_O'Connor.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Roderick_Paulus.PNG -o Roderick_Paulus.PNG
curl https://projects.thecity.nyc/covid-19-deaths-img/David_Perez.jpg -o David_Perez.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Lemuel_Sison.jpg -o Lemuel_Sison.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Robert_Thoering.jpg -o Robert_Thoering.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Donahue_Vargas.jpeg -o Donahue_Vargas.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Gabriella_Hernandez.jpeg -o Gabriella_Hernandez.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Ernesto_Hernandez.jpeg -o Ernesto_Hernandez.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Mudada_Kabir.jpg -o Mudada_Kabir.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Patrick_Patoir.jpeg -o Patrick_Patoir.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Eric_Sobel.png -o Eric_Sobel.png
curl https://projects.thecity.nyc/covid-19-deaths-img/Willis_Washington.jpg -o Willis_Washington.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Hui_Liang_Wen.jpg -o Hui_Liang_Wen.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Sal_Lombardo.jpg -o Sal_Lombardo.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Judy_Sampson_Avilez.jpg -o Judy_Sampson_Avilez.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Yakara_Beauvoir.jpeg -o Yakara_Beauvoir.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Pablo_Cruz.jpg -o Pablo_Cruz.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Arturo_Interiano.jpeg -o Arturo_Interiano.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Jody_Settle.jpg -o Jody_Settle.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Jules_Taylor.jpg -o Jules_Taylor.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Georgina_Aguirre.jpg -o Georgina_Aguirre.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Zaman_Ali.jpg -o Zaman_Ali.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Julio_Barrios.jpg -o Julio_Barrios.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Stephen_Candiloro.jpg -o Stephen_Candiloro.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Miguel_Guaman.jpg -o Miguel_Guaman.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Manuel_Guanaquiza.jpg -o Manuel_Guanaquiza.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Gregory_Hodge.PNG -o Gregory_Hodge.PNG
curl https://projects.thecity.nyc/covid-19-deaths-img/Michelle_Johnson.jpeg -o Michelle_Johnson.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Syed_Rahman.jpg -o Syed_Rahman.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Luis_Riascos.jpeg -o Luis_Riascos.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Richard_Johnson.jpg -o Richard_Johnson.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Diego_Agron.jpg -o Diego_Agron.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Tapan_Barua.jpg -o Tapan_Barua.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Fareeda_Beharry.jpeg -o Fareeda_Beharry.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Idris_Bey.PNG -o Idris_Bey.PNG
curl https://projects.thecity.nyc/covid-19-deaths-img/Ruel_DeJesus.jpeg -o Ruel_DeJesus.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Joseph_Fletcher.JPG -o Joseph_Fletcher.JPG
curl https://projects.thecity.nyc/covid-19-deaths-img/Mary_Minerly.jpg -o Mary_Minerly.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Juan_Ollarvide.jpg -o Juan_Ollarvide.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Brian_Saddler.png -o Brian_Saddler.png
curl https://projects.thecity.nyc/covid-19-deaths-img/Alfredo_Santos.jpg -o Alfredo_Santos.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Michael_Stevens.jpg -o Michael_Stevens.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Alex_Carrazana.jpg -o Alex_Carrazana.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Sharon_Bascom.jpg -o Sharon_Bascom.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Vanessa_Burkett.jpg -o Vanessa_Burkett.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Raul_Carmona.jpeg -o Raul_Carmona.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Ronnie_Cordero.jpg -o Ronnie_Cordero.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Edwin_Garcia.jpg -o Edwin_Garcia.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Paul_Gray.jpeg -o Paul_Gray.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Rainer_Kilian.jpeg -o Rainer_Kilian.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Maria_Victoria_Lucas.jpg -o Maria_Victoria_Lucas.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Lisa_Mack.jpg -o Lisa_Mack.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/William_Morris.jpeg -o William_Morris.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Angel_Pilligua.jpg -o Angel_Pilligua.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Promela_Suri.jpg -o Promela_Suri.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Mireya_Cardona.jpg -o Mireya_Cardona.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Marcos_Castro.jpg -o Marcos_Castro.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Nina_Marie_Favuzza.png -o Nina_Marie_Favuzza.png
curl https://projects.thecity.nyc/covid-19-deaths-img/Abul_Hossain.JPG -o Abul_Hossain.JPG
curl https://projects.thecity.nyc/covid-19-deaths-img/Yi_Gao_Huang.jpg -o Yi_Gao_Huang.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Anthony_Meoli.jpg -o Anthony_Meoli.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Adolfo_Motta.jpg -o Adolfo_Motta.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Frank_Orsini.jpg -o Frank_Orsini.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/William_Plantt.JPG -o William_Plantt.JPG
curl https://projects.thecity.nyc/covid-19-deaths-img/Antonio_Ramos.jpeg -o Antonio_Ramos.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Gurpaul_Singh.jpeg -o Gurpaul_Singh.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Romeo_Agtarap.jpg -o Romeo_Agtarap.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Seymour_Collins.jpg -o Seymour_Collins.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Gaetana_Deserto.jpg -o Gaetana_Deserto.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Sharan_Fernandez.jpg -o Sharan_Fernandez.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Carlos_Alfredo_Fernandez.jpg -o Carlos_Alfredo_Fernandez.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Karen_Garvin.jpg -o Karen_Garvin.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/John_Marchini.jpg -o John_Marchini.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Luis_Fernando_Marulanda.png -o Luis_Fernando_Marulanda.png
curl https://projects.thecity.nyc/covid-19-deaths-img/Carlton_Naughton.jpeg -o Carlton_Naughton.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/John_Redd.jpg -o John_Redd.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Richard_Seaberry.jpg -o Richard_Seaberry.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Antonio_Suarez.jpg -o Antonio_Suarez.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Manuel_Tito.jpg -o Manuel_Tito.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Ingird_Warner.jpeg -o Ingird_Warner.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Theodore_Campbell.jpeg -o Theodore_Campbell.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Stuart_Cohen.jpg -o Stuart_Cohen.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Jacob_Credell.jpg -o Jacob_Credell.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Elena_Caceres.JPG -o Elena_Caceres.JPG
curl https://projects.thecity.nyc/covid-19-deaths-img/Luis_Figueroa.jpg -o Luis_Figueroa.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Elisabeth_Rubert.jpg -o Elisabeth_Rubert.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Edward_Doty.jpeg -o Edward_Doty.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Stephanie_Gaston.jpg -o Stephanie_Gaston.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Luis_Martinez.jpg -o Luis_Martinez.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Lisa_Louise_Montanino.png -o Lisa_Louise_Montanino.png
curl https://projects.thecity.nyc/covid-19-deaths-img/Peter_Panayiotou.jpeg -o Peter_Panayiotou.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Naim_Tome.jpg -o Naim_Tome.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Fernando_Zapata.JPG -o Fernando_Zapata.JPG
curl https://projects.thecity.nyc/covid-19-deaths-img/Eloy_Calixto_Andon.jpg -o Eloy_Calixto_Andon.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Maria_Aragon.jpeg -o Maria_Aragon.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Charles_DeJesus.jpg -o Charles_DeJesus.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Muhammad_Iftekharuddin.jpg -o Muhammad_Iftekharuddin.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Rustico_Pasig.jpg -o Rustico_Pasig.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Maureen_Robinson_Morgan.png -o Maureen_Robinson_Morgan.png
curl https://projects.thecity.nyc/covid-19-deaths-img/Frances_Rudland1.jpg -o Frances_Rudland1.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Alphonse_Agovino.jpeg -o Alphonse_Agovino.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Alfonso_Chang.jpg -o Alfonso_Chang.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Michael_Dimin.JPG -o Michael_Dimin.JPG
curl https://projects.thecity.nyc/covid-19-deaths-img/Marc_Goodman.jpg -o Marc_Goodman.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Mohamed_Nezaam_Harun.jpeg -o Mohamed_Nezaam_Harun.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Patricia_Jackson.jpg -o Patricia_Jackson.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Victoria_Leon.jpg -o Victoria_Leon.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Paul_Lindner.png -o Paul_Lindner.png
curl https://projects.thecity.nyc/covid-19-deaths-img/Gisele_Menard.jpg -o Gisele_Menard.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Beatriz_Soler.jpeg -o Beatriz_Soler.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/David_Stone.jpg -o David_Stone.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Edwin_Valencia.jpg -o Edwin_Valencia.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Phyllis_Burkett.jpg -o Phyllis_Burkett.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Juan_Caban.jpg -o Juan_Caban.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Ezzard_Christopher.jpg -o Ezzard_Christopher.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Ralph_Gismondi.jpg -o Ralph_Gismondi.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Jose_L_Gonzalez.jpg -o Jose_L_Gonzalez.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Kenneth_Henderson.jpg -o Kenneth_Henderson.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Daniel_Karpus.jpg -o Daniel_Karpus.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Manuel_Ortiz.jpg -o Manuel_Ortiz.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Barbara_Richardson.jpg -o Barbara_Richardson.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Michael_Scura.jpg -o Michael_Scura.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Rosa_Villada.png -o Rosa_Villada.png
curl https://projects.thecity.nyc/covid-19-deaths-img/Cynthia_L_Adams.jpeg -o Cynthia_L_Adams.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Dominick_Brancato.jpg -o Dominick_Brancato.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Carmen_Calero.jpeg -o Carmen_Calero.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Robert_Joseph_Cavello.jpeg -o Robert_Joseph_Cavello.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Jay_Galst.jpg -o Jay_Galst.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Coralia_Galvez.jpg -o Coralia_Galvez.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Jose_Jaramillo.jpeg -o Jose_Jaramillo.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Marilu_Santiago.jpg -o Marilu_Santiago.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Kosta_Stefanopoulos.jpg -o Kosta_Stefanopoulos.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Charles_Thorpe.jpg -o Charles_Thorpe.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/John_Whyte.jpg -o John_Whyte.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Carlos_Acevedo.png -o Carlos_Acevedo.png
curl https://projects.thecity.nyc/covid-19-deaths-img/Samuel_Arbeeny.png -o Samuel_Arbeeny.png
curl https://projects.thecity.nyc/covid-19-deaths-img/Karen_Faulkner.jpg -o Karen_Faulkner.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Verona_Fraser.JPG -o Verona_Fraser.JPG
curl https://projects.thecity.nyc/covid-19-deaths-img/Beverly_Gray.jpeg -o Beverly_Gray.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Frank_lumini.jpg -o Frank_lumini.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Paul_McElearney.jpg -o Paul_McElearney.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Alfredo_Mescallado.jpg -o Alfredo_Mescallado.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Shirley_Ann_Miller.JPG -o Shirley_Ann_Miller.JPG
curl https://projects.thecity.nyc/covid-19-deaths-img/Liaquat_Mohammed.png -o Liaquat_Mohammed.png
curl https://projects.thecity.nyc/covid-19-deaths-img/Judy_Richheimer.jpg -o Judy_Richheimer.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Pablo_Rosas.jpeg -o Pablo_Rosas.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Ernesto_Sanchez.jpeg -o Ernesto_Sanchez.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Luis_Santos.jpg -o Luis_Santos.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Joseph_Daniel_Volcy.jpeg -o Joseph_Daniel_Volcy.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Lorraine_Bagwell.JPG -o Lorraine_Bagwell.JPG
curl https://projects.thecity.nyc/covid-19-deaths-img/Michael_A_Costanzo.jpg -o Michael_A_Costanzo.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Larry_DeVito.JPG -o Larry_DeVito.JPG
curl https://projects.thecity.nyc/covid-19-deaths-img/Leah_Dombe.jpeg -o Leah_Dombe.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Harvey_Fuchs.jpg -o Harvey_Fuchs.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Leroy_Hammett.jpeg -o Leroy_Hammett.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Jay_Hyman.jpg -o Jay_Hyman.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Gary_Jaeger.jpg -o Gary_Jaeger.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Elizabeth_Lamberty.jpg -o Elizabeth_Lamberty.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Mahmooda_Shaheen.jpg -o Mahmooda_Shaheen.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Rosemary_Sisco.jpg -o Rosemary_Sisco.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Antonio_Solomon.jpeg -o Antonio_Solomon.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Bradley_Stewart.jpg -o Bradley_Stewart.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Noreen_Johnson.jpg -o Noreen_Johnson.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Joaquin_Leon.jpeg -o Joaquin_Leon.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Richard_Litofsky.jpg -o Richard_Litofsky.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Carmen_Pacheco.JPG -o Carmen_Pacheco.JPG
curl https://projects.thecity.nyc/covid-19-deaths-img/Domingo_Perez_Rivera.jpg -o Domingo_Perez_Rivera.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Eileen_Ruiz.jpg -o Eileen_Ruiz.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Estelita_Solomon.jpeg -o Estelita_Solomon.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Joseph_Tranchina.jpg -o Joseph_Tranchina.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Frankie_Alli.jpg -o Frankie_Alli.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Isabella_Axelrod.jpg -o Isabella_Axelrod.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Ismael_Cabrera.jpg -o Ismael_Cabrera.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Felicia_Caceres.jpeg -o Felicia_Caceres.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Stuart_Richard_Cohen.jpg -o Stuart_Richard_Cohen.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Anthony_C_Dazzo.JPG -o Anthony_C_Dazzo.JPG
curl https://projects.thecity.nyc/covid-19-deaths-img/Rosemary_Guerrero.jpeg -o Rosemary_Guerrero.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Michael_Herron.jpg -o Michael_Herron.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Arthur_Lacker.PNG -o Arthur_Lacker.PNG
curl https://projects.thecity.nyc/covid-19-deaths-img/Corky_Lee.png -o Corky_Lee.png
curl https://projects.thecity.nyc/covid-19-deaths-img/Indarjit_Maraj.jpg -o Indarjit_Maraj.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Ronald_McKie.jpeg -o Ronald_McKie.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Albert_Petrocelli.jpg -o Albert_Petrocelli.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Raymond_Rosado.jpg -o Raymond_Rosado.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Luz_Santiago.jpeg -o Luz_Santiago.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Alan_Schoenberg.jpeg -o Alan_Schoenberg.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Emilio_Sosa.jpg -o Emilio_Sosa.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Rodolfo_Acevedo.jpg -o Rodolfo_Acevedo.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Christos_Arsenis.png -o Christos_Arsenis.png
curl https://projects.thecity.nyc/covid-19-deaths-img/Louis_Barbato.jpg -o Louis_Barbato.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Ivonne_Benoit.jpg -o Ivonne_Benoit.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Donato_Joseph_Cannella.png -o Donato_Joseph_Cannella.png
curl https://projects.thecity.nyc/covid-19-deaths-img/Carmen_Cruz.jpg -o Carmen_Cruz.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/John_Dunston_Jr.png -o John_Dunston_Jr.png
curl https://projects.thecity.nyc/covid-19-deaths-img/Felix_Escoto.jpeg -o Felix_Escoto.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Joseph_Mintah.jpg -o Joseph_Mintah.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Arthur_Nelson.jpeg -o Arthur_Nelson.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Gregory_Penny.jpg -o Gregory_Penny.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/David_Perez2.jpg -o David_Perez2.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Peggy_Wiltrout.jpg -o Peggy_Wiltrout.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Fook_Sheong_Wong.jpg -o Fook_Sheong_Wong.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Thomas_Crater.png -o Thomas_Crater.png
curl https://projects.thecity.nyc/covid-19-deaths-img/Jay_Goldstein.jpg -o Jay_Goldstein.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Mavis_Haywood.png -o Mavis_Haywood.png
curl https://projects.thecity.nyc/covid-19-deaths-img/Fareeda_Ann_Kadwani.jpg -o Fareeda_Ann_Kadwani.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Dale_Richard_Pon.jpg -o Dale_Richard_Pon.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Janine_Soleil.jpg -o Janine_Soleil.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/George_Stoney.jpg -o George_Stoney.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/James_Thompson.jpg -o James_Thompson.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Anthony_Bonelli.JPG -o Anthony_Bonelli.JPG
curl https://projects.thecity.nyc/covid-19-deaths-img/Ruth_Corbett.jpeg -o Ruth_Corbett.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Pedro_Flores.jpeg -o Pedro_Flores.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Lori_McDonald.jpg -o Lori_McDonald.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Elba_Ortiz.jpg -o Elba_Ortiz.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Joel_Shatzky.jpg -o Joel_Shatzky.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/David_Strug.JPG -o David_Strug.JPG
curl https://projects.thecity.nyc/covid-19-deaths-img/Rosa_Triguero.png -o Rosa_Triguero.png
curl https://projects.thecity.nyc/covid-19-deaths-img/Illuysha_Aminov.jpg -o Illuysha_Aminov.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Wilbert_Burkett.png -o Wilbert_Burkett.png
curl https://projects.thecity.nyc/covid-19-deaths-img/John_Buttner.jpeg -o John_Buttner.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/John_Crowe.jpg -o John_Crowe.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Iris_Cruz.jpg -o Iris_Cruz.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Christina_Danielo.jpg -o Christina_Danielo.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Jason_Fuchs.jpg -o Jason_Fuchs.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Brilla_Jarldane.jpg -o Brilla_Jarldane.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Jose_Manuel_Lugo_Castro.png -o Jose_Manuel_Lugo_Castro.png
curl https://projects.thecity.nyc/covid-19-deaths-img/Blanca_Mero.jpg -o Blanca_Mero.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Emelda_Rodriguez.jpg -o Emelda_Rodriguez.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Phyllis_Thompson.JPG -o Phyllis_Thompson.JPG
curl https://projects.thecity.nyc/covid-19-deaths-img/Rameschandra_Patel.jpeg -o Rameschandra_Patel.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Joseph_Anthony_Szalkiewicz.jpeg -o Joseph_Anthony_Szalkiewicz.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Edward_Antonio.jpg -o Edward_Antonio.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Carol_Cerabone.jpeg -o Carol_Cerabone.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Mary_Anne_Delong.png -o Mary_Anne_Delong.png
curl https://projects.thecity.nyc/covid-19-deaths-img/Purim_Isakov.jpg -o Purim_Isakov.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Harriet_Maio.jpeg -o Harriet_Maio.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Elizabeth_McCollum.jpeg -o Elizabeth_McCollum.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Rafael_Negron.jpg -o Rafael_Negron.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Aryeh_Norensberg.jpeg -o Aryeh_Norensberg.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Carmen_Silva.jpg -o Carmen_Silva.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Ada_Rivers.jpg -o Ada_Rivers.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Guido_Volcovici.jpg -o Guido_Volcovici.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Olga_M_Zayas.jpeg -o Olga_M_Zayas.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Alvaro_Bonilla.jpg -o Alvaro_Bonilla.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Oliver_Clarke.jpg -o Oliver_Clarke.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/John_Dearden.jpg -o John_Dearden.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Mark_Gabor.jpeg -o Mark_Gabor.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/BibiMaimoonNeisha_Khan.jpg -o BibiMaimoonNeisha_Khan.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Esteban_Matos.jpeg -o Esteban_Matos.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Ronald_O'Loughlin.png -o Ronald_O'Loughlin.png
curl https://projects.thecity.nyc/covid-19-deaths-img/Harold_Solomon.png -o Harold_Solomon.png
curl https://projects.thecity.nyc/covid-19-deaths-img/Clarence_Spann.jpg -o Clarence_Spann.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/John_Walter.jpg -o John_Walter.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Annie_Bailey.jpeg -o Annie_Bailey.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Eric_Bowen.jpeg -o Eric_Bowen.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Ok_Choi.jpeg -o Ok_Choi.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Evelyn_Harris.jpeg -o Evelyn_Harris.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Alma_Lillian_Marquez.jpeg -o Alma_Lillian_Marquez.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Antonia_Reynoso.jpeg -o Antonia_Reynoso.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Joe_Aloe.jpeg -o Joe_Aloe.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Pik_Chi_Chan.jpg -o Pik_Chi_Chan.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Richard_diLiberto.jpg -o Richard_diLiberto.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Elsa_Gomez.jpg -o Elsa_Gomez.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Annie_Ruth_Johnson.jpg -o Annie_Ruth_Johnson.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/William_Levy.jpg -o William_Levy.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Ernest_Morency.jpg -o Ernest_Morency.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Tobias_Noboa.png -o Tobias_Noboa.png
curl https://projects.thecity.nyc/covid-19-deaths-img/Ana_Ortiz.jpeg -o Ana_Ortiz.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Jeffrey_Paley.jpg -o Jeffrey_Paley.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Antonio_Pepenella.jpg -o Antonio_Pepenella.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Madu_Rao.jpeg -o Madu_Rao.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Nataliya_Rudnichenko.jpg -o Nataliya_Rudnichenko.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Ivan_Santana.png -o Ivan_Santana.png
curl https://projects.thecity.nyc/covid-19-deaths-img/Jesus_Sosa.jpg -o Jesus_Sosa.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Rosemary_Terio.jpg -o Rosemary_Terio.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Willamay_Thompson.jpg -o Willamay_Thompson.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Lynette_Woodland_Love.png -o Lynette_Woodland_Love.png
curl https://projects.thecity.nyc/covid-19-deaths-img/Stanley_Albert.jpg -o Stanley_Albert.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Charles_Burkett.jpeg -o Charles_Burkett.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Maria_Hernandez.jpeg -o Maria_Hernandez.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Gerard_Manolovici.jpg -o Gerard_Manolovici.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Elias_Melton.jpeg -o Elias_Melton.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Donald_Miller.JPG -o Donald_Miller.JPG
curl https://projects.thecity.nyc/covid-19-deaths-img/William_Negron.jpg -o William_Negron.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Lila_Weissman.jpg -o Lila_Weissman.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Robert_Zolnerzak.jpg -o Robert_Zolnerzak.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Dolores_Mena.JPG -o Dolores_Mena.JPG
curl https://projects.thecity.nyc/covid-19-deaths-img/Michael_Besser.jpg -o Michael_Besser.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Gerald_Bruskin.jpg -o Gerald_Bruskin.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Cristina_Lopez.jpg -o Cristina_Lopez.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Ralph_Martel.jpeg -o Ralph_Martel.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Jose_Rico.png -o Jose_Rico.png
curl https://projects.thecity.nyc/covid-19-deaths-img/Arlene_Schneidman.jpeg -o Arlene_Schneidman.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Olga_Vasquez.jpg -o Olga_Vasquez.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Gilbert_Burkett.jpg -o Gilbert_Burkett.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Andres_Diaz.jpeg -o Andres_Diaz.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Iola_Dunlap.png -o Iola_Dunlap.png
curl https://projects.thecity.nyc/covid-19-deaths-img/Stephen_Durnin.jpeg -o Stephen_Durnin.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Joseph_Ferris.jpeg -o Joseph_Ferris.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Ed_Fuld.jpg -o Ed_Fuld.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Paolo_Giusti.png -o Paolo_Giusti.png
curl https://projects.thecity.nyc/covid-19-deaths-img/Clifton_Howell.jpg -o Clifton_Howell.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Mohammad_Shamsul_Islam.jpg -o Mohammad_Shamsul_Islam.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Arturo_Noles.jpg -o Arturo_Noles.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Mario_Pobega.jpg -o Mario_Pobega.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Marie_Proto.jpg -o Marie_Proto.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Bala_Sennandan.jpeg -o Bala_Sennandan.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Chandrakant_Sheth.jpg -o Chandrakant_Sheth.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Maria_Arechua.png -o Maria_Arechua.png
curl https://projects.thecity.nyc/covid-19-deaths-img/Gloria_Barone.JPG -o Gloria_Barone.JPG
curl https://projects.thecity.nyc/covid-19-deaths-img/Laurice_Kasow.jpg -o Laurice_Kasow.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Manh_Nguyen.jpeg -o Manh_Nguyen.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Felipe_Ortiz.jpeg -o Felipe_Ortiz.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Maria_Lena_Pierre_Louis.jpeg -o Maria_Lena_Pierre_Louis.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Jack_Smith.png -o Jack_Smith.png
curl https://projects.thecity.nyc/covid-19-deaths-img/Anthony_Terio.jpeg -o Anthony_Terio.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Joan_Terrero.jpg -o Joan_Terrero.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Etta_Alston.jpg -o Etta_Alston.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Walter_Bailey.png -o Walter_Bailey.png
curl https://projects.thecity.nyc/covid-19-deaths-img/Terry_Collins.png -o Terry_Collins.png
curl https://projects.thecity.nyc/covid-19-deaths-img/Edith_Ecker.jpg -o Edith_Ecker.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Pedro_Muniz.JPG -o Pedro_Muniz.JPG
curl https://projects.thecity.nyc/covid-19-deaths-img/MariaRosa_Parrelli.jpeg -o MariaRosa_Parrelli.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Angie_Rosa.png -o Angie_Rosa.png
curl https://projects.thecity.nyc/covid-19-deaths-img/Accursio_Zagara.jpg -o Accursio_Zagara.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Julios_Adorno_Jr.jpg -o Julios_Adorno_Jr.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Mildred_Kunin.jpeg -o Mildred_Kunin.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Rose_Mary_Infantino.jpg -o Rose_Mary_Infantino.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Manuel_Rivera.jpg -o Manuel_Rivera.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Barbara_Cassella.jpeg -o Barbara_Cassella.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Thomas_Ecker.JPG -o Thomas_Ecker.JPG
curl https://projects.thecity.nyc/covid-19-deaths-img/Irving_Engelson.jpg -o Irving_Engelson.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Phyllis_Fioravanti.jpg -o Phyllis_Fioravanti.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Dionysios_Kotsonis.JPG -o Dionysios_Kotsonis.JPG
curl https://projects.thecity.nyc/covid-19-deaths-img/Cesar_Morales.JPG -o Cesar_Morales.JPG
curl https://projects.thecity.nyc/covid-19-deaths-img/Carmen_Muniz.JPG -o Carmen_Muniz.JPG
curl https://projects.thecity.nyc/covid-19-deaths-img/Carmen_Perez_Abreu.png -o Carmen_Perez_Abreu.png
curl https://projects.thecity.nyc/covid-19-deaths-img/Gilda_Villaman.JPG -o Gilda_Villaman.JPG
curl https://projects.thecity.nyc/covid-19-deaths-img/Miguel_Calderon.JPG -o Miguel_Calderon.JPG
curl https://projects.thecity.nyc/covid-19-deaths-img/Lenore_Corcoran.jpg -o Lenore_Corcoran.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Martha_Diaz.jpg -o Martha_Diaz.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Lucy_Nicolelis.jpeg -o Lucy_Nicolelis.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Lucille_Tappe.png -o Lucille_Tappe.png
curl https://projects.thecity.nyc/covid-19-deaths-img/Harold_Blake.jpg -o Harold_Blake.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Candida_Caraballo.jpg -o Candida_Caraballo.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Rosario_Gonzalez.png -o Rosario_Gonzalez.png
curl https://projects.thecity.nyc/covid-19-deaths-img/Maria_Iasiuolo.jpg -o Maria_Iasiuolo.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Annette_Marks.jpg -o Annette_Marks.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Theresa_Estelle_Morris.png -o Theresa_Estelle_Morris.png
curl https://projects.thecity.nyc/covid-19-deaths-img/Judith_Patocs.jpg -o Judith_Patocs.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Irma_Sanchez.jpg -o Irma_Sanchez.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Alexander_Tabarovsky.png -o Alexander_Tabarovsky.png
curl https://projects.thecity.nyc/covid-19-deaths-img/Margaret_Civers.jpg -o Margaret_Civers.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Juan_Garcia_Quinones.jpg -o Juan_Garcia_Quinones.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Albert_Goodgold.jpg -o Albert_Goodgold.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Chandrawati_Gurdiyal.jpeg -o Chandrawati_Gurdiyal.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Khana_Vorovich.jpeg -o Khana_Vorovich.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/George_Wolf.jpg -o George_Wolf.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Robert_Brogan.jpg -o Robert_Brogan.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Agatha_Fina.jpg -o Agatha_Fina.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Jennie_Graziano.jpg -o Jennie_Graziano.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/James_L_Hutcherson.JPG -o James_L_Hutcherson.JPG
curl https://projects.thecity.nyc/covid-19-deaths-img/Ligia_Pita_Menzies.jpg -o Ligia_Pita_Menzies.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/John_Ruvo.jpg -o John_Ruvo.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Carmelina_Ceballos.jpg -o Carmelina_Ceballos.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Marion_Gavin.JPG -o Marion_Gavin.JPG
curl https://projects.thecity.nyc/covid-19-deaths-img/Ann_Kross.jpg -o Ann_Kross.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Luba_Wengersky.jpg -o Luba_Wengersky.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Irene_Zorfas.JPG -o Irene_Zorfas.JPG
curl https://projects.thecity.nyc/covid-19-deaths-img/Emily_Savitsky.jpg -o Emily_Savitsky.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Robert_Wolfson.jpg -o Robert_Wolfson.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Lillian_Lazar.jpg -o Lillian_Lazar.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Miriam_Stolzenberg.JPG -o Miriam_Stolzenberg.JPG
curl https://projects.thecity.nyc/covid-19-deaths-img/Edwin_Weintraub.JPG -o Edwin_Weintraub.JPG
curl https://projects.thecity.nyc/covid-19-deaths-img/Evelyn_Bullcock.jpeg -o Evelyn_Bullcock.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Etta_Rebecca_Bush.png -o Etta_Rebecca_Bush.png
curl https://projects.thecity.nyc/covid-19-deaths-img/Harold_Grossman.jpg -o Harold_Grossman.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Vito_Brancato.jpg -o Vito_Brancato.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Candida_Rosa_Molina.jpeg -o Candida_Rosa_Molina.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Louis_Schmidt.jpg -o Louis_Schmidt.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Miriam_Kerpen.jpg -o Miriam_Kerpen.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Sylvia_Lieber.png -o Sylvia_Lieber.png
curl https://projects.thecity.nyc/covid-19-deaths-img/Millie_Belle_Berry.jpg -o Millie_Belle_Berry.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Vidal_Cruz.jpg -o Vidal_Cruz.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Ramon_Gonzalez.jpg -o Ramon_Gonzalez.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Clyde_William_Henry.jpg -o Clyde_William_Henry.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Laura_TaylorHowell.jpg -o Laura_TaylorHowell.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Melody_Reed.jpg -o Melody_Reed.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Agustin_Salvador.jpeg -o Agustin_Salvador.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/William_Scanlan.jpg -o William_Scanlan.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/James_Weber.jpeg -o James_Weber.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Julian_Clyde_Weston.jpg -o Julian_Clyde_Weston.jpg
