curl https://projects.thecity.nyc/covid-19-deaths-img/Shaimeek_Frazier.jpg -o Shaimeek_Frazier.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/David_Rivera.jpeg -o David_Rivera.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Michelle_Alexander.jpg -o Michelle_Alexander.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Avinaash_Takdari.jpg -o Avinaash_Takdari.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Miguel_Almarante.jpg -o Miguel_Almarante.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Frantz_Vital.jpg -o Frantz_Vital.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Luke_Workoff.png -o Luke_Workoff.png
curl https://projects.thecity.nyc/covid-19-deaths-img/Juan_Rodriguez.jpg -o Juan_Rodriguez.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Jonathon_Davis.png -o Jonathon_Davis.png
curl https://projects.thecity.nyc/covid-19-deaths-img/Joel_Gomez.jpg -o Joel_Gomez.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Dustin_Petrie.jpg -o Dustin_Petrie.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Rovin_Smith.jpeg -o Rovin_Smith.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Clinton_Washington.jpg -o Clinton_Washington.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Robert_Cardona.PNG -o Robert_Cardona.PNG
curl https://projects.thecity.nyc/covid-19-deaths-img/Danny_Camacho.jpg -o Danny_Camacho.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Pablo_Garcia.JPG -o Pablo_Garcia.JPG
curl https://projects.thecity.nyc/covid-19-deaths-img/Luis_Liz.jpeg -o Luis_Liz.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Evelyn_Rivera.jpg -o Evelyn_Rivera.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Randip_Minhas.JPG -o Randip_Minhas.JPG
curl https://projects.thecity.nyc/covid-19-deaths-img/Kelly_Wong.jpg -o Kelly_Wong.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Luis_Rivera.jpeg -o Luis_Rivera.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Robert_Nathan.jpg -o Robert_Nathan.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Robert_Papik.png -o Robert_Papik.png
curl https://projects.thecity.nyc/covid-19-deaths-img/Adalberto_Lebron.jpeg -o Adalberto_Lebron.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Juan_Vazquez.jpg -o Juan_Vazquez.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Bashir_Ajaz_Mohammed.jpeg -o Bashir_Ajaz_Mohammed.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Charles_Burrows.jpg -o Charles_Burrows.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Arthur_Hurwitz.jpg -o Arthur_Hurwitz.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Richard_Lenihan.jpg -o Richard_Lenihan.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Tracey_Murchison.jpg -o Tracey_Murchison.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Antonietta_Florio.png -o Antonietta_Florio.png
curl https://projects.thecity.nyc/covid-19-deaths-img/Jose_Hernandez.jpg -o Jose_Hernandez.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Thankachan_Mathai.jpg -o Thankachan_Mathai.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Tim_Montgomery.jpg -o Tim_Montgomery.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/David_Perez.jpg -o David_Perez.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Lemuel_Sison.jpg -o Lemuel_Sison.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Robert_Thoering.jpg -o Robert_Thoering.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Gabriella_Hernandez.jpeg -o Gabriella_Hernandez.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Ernesto_Hernandez.jpeg -o Ernesto_Hernandez.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Mudada_Kabir.jpg -o Mudada_Kabir.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Patrick_Patoir.jpeg -o Patrick_Patoir.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Eric_Sobel.png -o Eric_Sobel.png
curl https://projects.thecity.nyc/covid-19-deaths-img/Willis_Washington.jpg -o Willis_Washington.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Sal_Lombardo.jpg -o Sal_Lombardo.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Jody_Settle.jpg -o Jody_Settle.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Jules_Taylor.jpg -o Jules_Taylor.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Miguel_Guaman.jpg -o Miguel_Guaman.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Manuel_Guanaquiza.jpg -o Manuel_Guanaquiza.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Gregory_Hodge.PNG -o Gregory_Hodge.PNG
curl https://projects.thecity.nyc/covid-19-deaths-img/Michelle_Johnson.jpeg -o Michelle_Johnson.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Syed_Rahman.jpg -o Syed_Rahman.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Luis_Riascos.jpeg -o Luis_Riascos.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Richard_Johnson.jpg -o Richard_Johnson.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Fareeda_Beharry.jpeg -o Fareeda_Beharry.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Idris_Bey.PNG -o Idris_Bey.PNG
curl https://projects.thecity.nyc/covid-19-deaths-img/Joseph_Fletcher.JPG -o Joseph_Fletcher.JPG
curl https://projects.thecity.nyc/covid-19-deaths-img/Mary_Minerly.jpg -o Mary_Minerly.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Juan_Ollarvide.jpg -o Juan_Ollarvide.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Brian_Saddler.png -o Brian_Saddler.png
curl https://projects.thecity.nyc/covid-19-deaths-img/Michael_Stevens.jpg -o Michael_Stevens.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Alex_Carrazana.jpg -o Alex_Carrazana.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Sharon_Bascom.jpg -o Sharon_Bascom.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Raul_Carmona.jpeg -o Raul_Carmona.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Mireya_Cardona.jpg -o Mireya_Cardona.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Marcos_Castro.jpg -o Marcos_Castro.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Abul_Hossain.JPG -o Abul_Hossain.JPG
curl https://projects.thecity.nyc/covid-19-deaths-img/Yi_Gao_Huang.jpg -o Yi_Gao_Huang.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Anthony_Meoli.jpg -o Anthony_Meoli.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Frank_Orsini.jpg -o Frank_Orsini.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Gaetana_Deserto.jpg -o Gaetana_Deserto.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Karen_Garvin.jpg -o Karen_Garvin.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/John_Redd.jpg -o John_Redd.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Richard_Seaberry.jpg -o Richard_Seaberry.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Ingird_Warner.jpeg -o Ingird_Warner.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Jacob_Credell.jpg -o Jacob_Credell.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Luis_Figueroa.jpg -o Luis_Figueroa.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Elisabeth_Rubert.jpg -o Elisabeth_Rubert.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Edward_Doty.jpeg -o Edward_Doty.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Luis_Martinez.jpg -o Luis_Martinez.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Lisa_Louise_Montanino.png -o Lisa_Louise_Montanino.png
curl https://projects.thecity.nyc/covid-19-deaths-img/Peter_Panayiotou.jpeg -o Peter_Panayiotou.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Fernando_Zapata.JPG -o Fernando_Zapata.JPG
curl https://projects.thecity.nyc/covid-19-deaths-img/Eloy_Calixto_Andon.jpg -o Eloy_Calixto_Andon.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Maria_Aragon.jpeg -o Maria_Aragon.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Rustico_Pasig.jpg -o Rustico_Pasig.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Alphonse_Agovino.jpeg -o Alphonse_Agovino.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Michael_Dimin.JPG -o Michael_Dimin.JPG
curl https://projects.thecity.nyc/covid-19-deaths-img/Marc_Goodman.jpg -o Marc_Goodman.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Gisele_Menard.jpg -o Gisele_Menard.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Juan_Caban.jpg -o Juan_Caban.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Ezzard_Christopher.jpg -o Ezzard_Christopher.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Ralph_Gismondi.jpg -o Ralph_Gismondi.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Kenneth_Henderson.jpg -o Kenneth_Henderson.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Manuel_Ortiz.jpg -o Manuel_Ortiz.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Barbara_Richardson.jpg -o Barbara_Richardson.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Michael_Scura.jpg -o Michael_Scura.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Cynthia_L_Adams.jpeg -o Cynthia_L_Adams.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Carmen_Calero.jpeg -o Carmen_Calero.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Jay_Galst.jpg -o Jay_Galst.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Marilu_Santiago.jpg -o Marilu_Santiago.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Charles_Thorpe.jpg -o Charles_Thorpe.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/John_Whyte.jpg -o John_Whyte.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Samuel_Arbeeny.png -o Samuel_Arbeeny.png
curl https://projects.thecity.nyc/covid-19-deaths-img/Verona_Fraser.JPG -o Verona_Fraser.JPG
curl https://projects.thecity.nyc/covid-19-deaths-img/Beverly_Gray.jpeg -o Beverly_Gray.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Shirley_Ann_Miller.JPG -o Shirley_Ann_Miller.JPG
curl https://projects.thecity.nyc/covid-19-deaths-img/Judy_Richheimer.jpg -o Judy_Richheimer.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Pablo_Rosas.jpeg -o Pablo_Rosas.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Joseph_Daniel_Volcy.jpeg -o Joseph_Daniel_Volcy.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Lorraine_Bagwell.JPG -o Lorraine_Bagwell.JPG
curl https://projects.thecity.nyc/covid-19-deaths-img/Larry_DeVito.JPG -o Larry_DeVito.JPG
curl https://projects.thecity.nyc/covid-19-deaths-img/Harvey_Fuchs.jpg -o Harvey_Fuchs.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Jay_Hyman.jpg -o Jay_Hyman.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Gary_Jaeger.jpg -o Gary_Jaeger.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Elizabeth_Lamberty.jpg -o Elizabeth_Lamberty.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Mahmooda_Shaheen.jpg -o Mahmooda_Shaheen.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Rosemary_Sisco.jpg -o Rosemary_Sisco.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Richard_Litofsky.jpg -o Richard_Litofsky.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Joseph_Tranchina.jpg -o Joseph_Tranchina.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Isabella_Axelrod.jpg -o Isabella_Axelrod.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Ismael_Cabrera.jpg -o Ismael_Cabrera.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Anthony_C_Dazzo.JPG -o Anthony_C_Dazzo.JPG
curl https://projects.thecity.nyc/covid-19-deaths-img/Rosemary_Guerrero.jpeg -o Rosemary_Guerrero.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Arthur_Lacker.PNG -o Arthur_Lacker.PNG
curl https://projects.thecity.nyc/covid-19-deaths-img/Indarjit_Maraj.jpg -o Indarjit_Maraj.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Albert_Petrocelli.jpg -o Albert_Petrocelli.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Alan_Schoenberg.jpeg -o Alan_Schoenberg.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Emilio_Sosa.jpg -o Emilio_Sosa.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Louis_Barbato.jpg -o Louis_Barbato.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Ivonne_Benoit.jpg -o Ivonne_Benoit.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Arthur_Nelson.jpeg -o Arthur_Nelson.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/David_Perez2.jpg -o David_Perez2.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Fook_Sheong_Wong.jpg -o Fook_Sheong_Wong.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Thomas_Crater.png -o Thomas_Crater.png
curl https://projects.thecity.nyc/covid-19-deaths-img/Jay_Goldstein.jpg -o Jay_Goldstein.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Fareeda_Ann_Kadwani.jpg -o Fareeda_Ann_Kadwani.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Dale_Richard_Pon.jpg -o Dale_Richard_Pon.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Janine_Soleil.jpg -o Janine_Soleil.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/James_Thompson.jpg -o James_Thompson.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Anthony_Bonelli.JPG -o Anthony_Bonelli.JPG
curl https://projects.thecity.nyc/covid-19-deaths-img/Ruth_Corbett.jpeg -o Ruth_Corbett.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Pedro_Flores.jpeg -o Pedro_Flores.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Lori_McDonald.jpg -o Lori_McDonald.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Joel_Shatzky.jpg -o Joel_Shatzky.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Illuysha_Aminov.jpg -o Illuysha_Aminov.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Iris_Cruz.jpg -o Iris_Cruz.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Christina_Danielo.jpg -o Christina_Danielo.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Jason_Fuchs.jpg -o Jason_Fuchs.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Brilla_Jarldane.jpg -o Brilla_Jarldane.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Blanca_Mero.jpg -o Blanca_Mero.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Emelda_Rodriguez.jpg -o Emelda_Rodriguez.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Phyllis_Thompson.JPG -o Phyllis_Thompson.JPG
curl https://projects.thecity.nyc/covid-19-deaths-img/Elizabeth_McCollum.jpeg -o Elizabeth_McCollum.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Carmen_Silva.jpg -o Carmen_Silva.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Ada_Rivers.jpg -o Ada_Rivers.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Guido_Volcovici.jpg -o Guido_Volcovici.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/John_Dearden.jpg -o John_Dearden.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/BibiMaimoonNeisha_Khan.jpg -o BibiMaimoonNeisha_Khan.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Esteban_Matos.jpeg -o Esteban_Matos.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Ronald_O'Loughlin.png -o Ronald_O'Loughlin.png
curl https://projects.thecity.nyc/covid-19-deaths-img/Clarence_Spann.jpg -o Clarence_Spann.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/John_Walter.jpg -o John_Walter.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Ok_Choi.jpeg -o Ok_Choi.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Antonia_Reynoso.jpeg -o Antonia_Reynoso.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Joe_Aloe.jpeg -o Joe_Aloe.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Pik_Chi_Chan.jpg -o Pik_Chi_Chan.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Elsa_Gomez.jpg -o Elsa_Gomez.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Ernest_Morency.jpg -o Ernest_Morency.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Ana_Ortiz.jpeg -o Ana_Ortiz.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Antonio_Pepenella.jpg -o Antonio_Pepenella.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Nataliya_Rudnichenko.jpg -o Nataliya_Rudnichenko.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Rosemary_Terio.jpg -o Rosemary_Terio.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Stanley_Albert.jpg -o Stanley_Albert.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Maria_Hernandez.jpeg -o Maria_Hernandez.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Gerard_Manolovici.jpg -o Gerard_Manolovici.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Elias_Melton.jpeg -o Elias_Melton.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Lila_Weissman.jpg -o Lila_Weissman.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Robert_Zolnerack.jpg -o Robert_Zolnerack.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Dolores_Mena.JPG -o Dolores_Mena.JPG
curl https://projects.thecity.nyc/covid-19-deaths-img/Michael_Besser.jpg -o Michael_Besser.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Ralph_Martel.jpeg -o Ralph_Martel.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Jose_Rico.png -o Jose_Rico.png
curl https://projects.thecity.nyc/covid-19-deaths-img/Arlene_Schneidman.jpeg -o Arlene_Schneidman.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Olga_Vasquez.jpg -o Olga_Vasquez.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Andres_Diaz.jpeg -o Andres_Diaz.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Ed_Fuld.jpg -o Ed_Fuld.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Mario_Pobega.jpg -o Mario_Pobega.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Chandrakant_Sheth.jpg -o Chandrakant_Sheth.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Laurice_Kasow.jpg -o Laurice_Kasow.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Anthony_Terio.jpeg -o Anthony_Terio.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Joan_Terrero.jpg -o Joan_Terrero.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Etta_Alston.jpg -o Etta_Alston.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Edith_Ecker.jpg -o Edith_Ecker.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Pedro_Muniz.JPG -o Pedro_Muniz.JPG
curl https://projects.thecity.nyc/covid-19-deaths-img/MariaRosa_Parrelli.jpeg -o MariaRosa_Parrelli.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Mildred_Kunin.jpeg -o Mildred_Kunin.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Rose_Mary_Infantino.jpg -o Rose_Mary_Infantino.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Thomas_Ecker.JPG -o Thomas_Ecker.JPG
curl https://projects.thecity.nyc/covid-19-deaths-img/Irving_Engelson.jpg -o Irving_Engelson.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Phyllis_Fioravanti.jpg -o Phyllis_Fioravanti.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Dionysios_Kotsonis.JPG -o Dionysios_Kotsonis.JPG
curl https://projects.thecity.nyc/covid-19-deaths-img/Carmen_Muniz.JPG -o Carmen_Muniz.JPG
curl https://projects.thecity.nyc/covid-19-deaths-img/Miguel_Calderon.JPG -o Miguel_Calderon.JPG
curl https://projects.thecity.nyc/covid-19-deaths-img/Lenore_Corcoran.jpg -o Lenore_Corcoran.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Martha_Diaz.jpg -o Martha_Diaz.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Lucy_Nicolelis.jpeg -o Lucy_Nicolelis.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Harold_Blake.jpg -o Harold_Blake.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Rosario_Gonzalez.png -o Rosario_Gonzalez.png
curl https://projects.thecity.nyc/covid-19-deaths-img/Theresa_Estelle_Morris.png -o Theresa_Estelle_Morris.png
curl https://projects.thecity.nyc/covid-19-deaths-img/Judith_Patocs.jpg -o Judith_Patocs.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Khana_Vorovich.jpeg -o Khana_Vorovich.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Agatha_Fina.jpg -o Agatha_Fina.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Jennie_Graziano.jpg -o Jennie_Graziano.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/James_L_Hutcherson.JPG -o James_L_Hutcherson.JPG
curl https://projects.thecity.nyc/covid-19-deaths-img/Marion_Gavin.JPG -o Marion_Gavin.JPG
curl https://projects.thecity.nyc/covid-19-deaths-img/Ann_Kross.jpg -o Ann_Kross.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Emily_Savitsky.jpg -o Emily_Savitsky.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Robert_Wolfson.jpg -o Robert_Wolfson.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Miriam_Stolzenberg.JPG -o Miriam_Stolzenberg.JPG
curl https://projects.thecity.nyc/covid-19-deaths-img/Evelyn_Bullcock.jpeg -o Evelyn_Bullcock.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/Etta_Rebecca_Bush.png -o Etta_Rebecca_Bush.png
curl https://projects.thecity.nyc/covid-19-deaths-img/Harold_Grossman.jpg -o Harold_Grossman.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Louis_Schmidt.jpg -o Louis_Schmidt.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Vidal_Cruz.jpg -o Vidal_Cruz.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/John_Dunston_Jr.png -o John_Dunston_Jr.png
curl https://projects.thecity.nyc/covid-19-deaths-img/Clyde_William_Henry.jpg -o Clyde_William_Henry.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Melody_Reed.jpg -o Melody_Reed.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Agustin_Salvador.jpeg -o Agustin_Salvador.jpeg
curl https://projects.thecity.nyc/covid-19-deaths-img/William_Scanlan.jpg -o William_Scanlan.jpg
curl https://projects.thecity.nyc/covid-19-deaths-img/Julian_Clyde_Weston.jpg -o Julian_Clyde_Weston.jpg